### ISSUE TITLE
ensure duplicate names are handled properly

### ISSUE THREAD

**Issue by michaelficarra** [jeffmo/es-class-properties#9]
``` js
class A {
  b = f();
  b = g();
}
```

This needs to not error defining `b` on instances of `A` twice, and needs to evaluate `f()` and `g()` each time `A` is constructed. The value of fresh instances of `A` should be the return value of `g()`.

**Comment by jeffmo** [comment]
Currently, with `configurable: false`, duplicate properties will error at runtime unless the values are the `===`.

[`configurability` is still a topic of debate](https://github.com/jeffmo/es-class-public-fields/issues/36), but I believe this issue was opened to address an issue with the original design where we could queue a set of instructions to be executed at instantiation time -- where the set was keyed by the property name (i.e. eliminating the execution of `f()` from ever happening).

This is no longer the case since we [no longer store the initialization instructions by the property name](https://tc39.github.io/proposal-class-public-fields/#runtime-semantics-class-definition-evaluation)
